version: '3.1'

services:

  nginx:
    container_name: 'nginx'
    image: 'nginx:latest'
    restart: 'always'
    # network_mode: 'host'
    ports:
      - 80:80
      - 443:443
    volumes: 
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/nginx-entrypoint.sh:/docker-entrypoint.d/nginx-entrypoint.sh:ro'
    depends_on:
      - server_app

  # postgres:
  #   container_name: 'postgres'
  #   image: 'postgres:latest'
  #   restart: 'always'
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: 'qwerty'
  #     POSTGRES_USER: 'postgres'
  #     POSTGRES_DB: 'baza'
    # volumes:
    #   - ./db/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #    - 27017:27017
  #   environment:
  #       MONGO_INITDB_ROOT_USERNAME: mongo
  #       MONGO_INITDB_ROOT_PASSWORD: password


  server_app:
    container_name: 'server_app'
    restart: 'always'
    build: 
      dockerfile: 'Dockerfile'
      context: './server'
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    # depends_on:
    #   - mongo